import SwiftUI

/// Developer / full-access picker for the backend chat-completion provider.
/// Lists only providers the server holds keys for (from `RemoteConfigService`);
/// selecting one persists to `UserSettings.chatProvider`, which the AI routes
/// honor server-side.
struct AIProviderPickerView: View {
    let available: [AIProvider]
    let serverDefault: AIProvider?
    let selected: AIProvider?
    let onSelect: (AIProvider) -> Void

    @Environment(\.dismiss) private var dismiss

    var body: some View {
        NavigationStack {
            ZStack {
                IAAppBackground()

                ScrollView {
                    VStack(alignment: .leading, spacing: IATheme.spacing16) {
                        Text("Answers are generated by this provider. API keys stay on the server — only developer accounts can switch.")
                            .font(IATypography.bodyMedium)
                            .foregroundStyle(IATheme.textSecondary)
                            .padding(.horizontal, 4)

                        VStack(spacing: 0) {
                            ForEach(Array(available.enumerated()), id: \.element) { index, provider in
                                Button {
                                    onSelect(provider)
                                    dismiss()
                                } label: {
                                    row(for: provider)
                                }
                                .buttonStyle(.plain)

                                if index < available.count - 1 {
                                    Divider().padding(.leading, 54)
                                }
                            }
                        }
                        .padding(.vertical, 8)
                        .padding(.horizontal, 14)
                        .background(
                            RoundedRectangle(cornerRadius: IATheme.radiusLarge, style: .continuous)
                                .fill(IATheme.surfaceWhite)
                        )
                        .overlay {
                            RoundedRectangle(cornerRadius: IATheme.radiusLarge, style: .continuous)
                                .stroke(IATheme.outlineVariant, lineWidth: 1)
                        }
                    }
                    .padding(.horizontal, IATheme.spacing20)
                    .padding(.vertical, IATheme.spacing20)
                }
                .iaScrollablePage()
            }
            .navigationTitle("AI Provider")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button("Done") { dismiss() }
                }
            }
        }
    }

    @ViewBuilder
    private func row(for provider: AIProvider) -> some View {
        HStack(spacing: 14) {
            Circle()
                .fill(IATheme.accent.opacity(0.12))
                .frame(width: 40, height: 40)
                .overlay {
                    Image(systemName: provider.iconName)
                        .font(.system(size: 16, weight: .semibold))
                        .foregroundStyle(IATheme.accent)
                }

            VStack(alignment: .leading, spacing: 2) {
                HStack(spacing: 6) {
                    Text(provider.displayName)
                        .font(IATypography.bodyLarge)
                        .foregroundStyle(IATheme.textPrimary)

                    if provider == serverDefault {
                        Text("Default")
                            .font(IATypography.labelSmall)
                            .foregroundStyle(IATheme.textTertiary)
                            .padding(.horizontal, 6)
                            .padding(.vertical, 2)
                            .background(
                                Capsule().fill(IATheme.outlineVariant.opacity(0.3))
                            )
                    }
                }

                Text(provider.description)
                    .font(IATypography.labelSmall)
                    .foregroundStyle(IATheme.textSecondary)
                    .fixedSize(horizontal: false, vertical: true)
            }

            Spacer(minLength: 8)

            if provider == selected {
                Image(systemName: "checkmark.circle.fill")
                    .font(.system(size: 18, weight: .semibold))
                    .foregroundStyle(IATheme.accent)
            }
        }
        .padding(.vertical, 8)
        .contentShape(Rectangle())
    }
}
